[package]
name = "takkie-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[[bin]]
name = "takkie"
path = "src/main.rs"

[dependencies]
chrono = "0.4"
cpal = { workspace = true }
crossterm = "0.28"
ratatui = "0.28"
takkie-engine = { path = "../takkie-engine" }

[lints]
workspace = true
