[package]
name = "takkie-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
arc-swap = "1"
cpal = "0.17.0"
crossbeam-channel = { workspace = true }
if-addrs = "0.15"
log = "0.4"
mdns-sd = "0.21"
opus = "0.4"
rtrb = "0.4"
rubato = "5.0.1"
socket2 = "0.6"
takkie-core = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
